name: 🕊️ Holub Evžen
on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Filename (without extension)'
        required: true
        default: ''
      content:
        description: 'Content (JSON data)'
        required: true
        default: ''
      nickname:
        description: 'Nickname'
        required: true
        default: ''

jobs:
  create_json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    
    - name: Create a json file
      run: |
        mkdir -p -- "_hall"
        cd _hall
        echo '${{ github.event.inputs.content }}' > ${{ github.event.inputs.filename }}.json
        cat ${{ github.event.inputs.filename }}.json
        
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TOKEN }}
        commit-message: Add new Evzen adventure
        committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: new-adventure-${{ github.event.inputs.filename }}
        delete-branch: true
        title: 'A new Evzen adventure request `${{ github.event.inputs.nickname }}`'
        body: |
          | KEY | VALUE |
          | ------ | ---------- |
          | nickname | **${{ fromJSON(github.event.inputs.content).nickname }}** |
          | score | `${{ fromJSON(github.event.inputs.content).score }}` |
          | timestamp | ${{ fromJSON(github.event.inputs.content).timestamp }} |
          
          Filename: ${{ github.event.inputs.filename }}.json
          
          ```json
          ${{ toJSON(fromJSON(github.event.inputs.content)) }}
          ```
        labels: |
          evzen
        reviewers: petrkucerak
        draft: false
